# -*- coding: utf-8 -*-
"""song recommender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YD95BQClW9mzN2IvPI_3sD-W_VzP3T8A
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('song1.csv')
df.columns = ["user_id", "song_id", "count"]
df.head(100)

print(df.shape)

print(df["song_id"].value_counts())

song_id_flat = df["song_id"].to_numpy()

print(len(song_id_flat))

song_id_flat = np.unique(song_id_flat)
song_id_flat = song_id_flat[0:10001]
print(len(song_id_flat))

ndf = pd.read_csv('SongCSV.csv')

song_dtst = ndf.loc[:,["SongID", "AlbumID", "AlbumName", "Title", "Year"]]

song_dtst['song_id'] = song_id_flat

song_dtst.head()

final_dtst = pd.merge(df, song_dtst, on='song_id')

final_dtst = final_dtst.drop(['SongID'], axis=1)

final_dtst.head()

print(final_dtst.shape)

print(final_dtst["song_id"].value_counts().shape)